use_default_settings: true

search:
  formats:
    - html
    - json

server:
  secret_key: "content-machine-searxng-2026"
  limiter: false
  image_proxy: false
  port: 8080
  bind_address: "0.0.0.0"
